export default {
  PRIVATE_KEY_NULL: 'private key is null.',
  PRIVATE_KEY_ERROR: 'private key is not correct.',
  GENERATION_HASH_NULL: 'generation hash key is null.',
  GENERATION_HASH_ERROR: 'generation hash is not correct.',
  PUBLIC_KEY_NULL: 'public key is null.',
  PUBLIC_KEY_ERROR: 'public key is not correct.',
  ADDRESS_NULL: 'address is null.',
  ADDRESS_ERROR: 'address is not correct.',
  TX_AMOUNT_ERROR: 'tx amount can not be less than 0.',
  MAX_FEE_ERROR: 'max fee can not be less than 0',
  MIN_APPROVAL_ERROR: 'min approval can not be less than 0',
  MIN_REMOVAL_ERROR: 'min removal can not be less than 0',
  FILTER_LIST_NULL: 'no filter exits.',
  MOSAIC_ERROR: 'mosaic id is not correct',
  MOSAIC_NULL: 'mosaic id is null',
  NO_COSIGNER: 'no cosigner exists in the list.',
  TOO_MUCH_COSIGNER: 'multisig accounts can have up to 10 cosigners.',
  REMOVAL_TOO_SMALL: 'removal delta is too small',
  APPROVAL_TOO_SMALL: 'approval delta is too small',
  REMOVAL_TOO_BIG: 'removal delta is too big',
  APPROVAL_TOO_BIG: 'removal delta is too big',
  TOO_LESS_COSIGNERS: 'cosigner list will be less than 0 after this transaction',
  TOO_MANY_COSIGNERS: 'cosigner list will be more than 10 after this transaction',
};
